# How to init submodule
# git submodule update --init --recursive
# git submodule update --remote --merge

# How to use it?
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3'
services:
  memorush-spring:
    networks:
      - nginx-proxy-manager_default

  memorush-react:
    networks:
      - nginx-proxy-manager_default

  memorush-db:
    networks:
      - nginx-proxy-manager_default

  memorush-pgadmin:
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true

volumes:
  memorush-db:
  memorush-pgadmin: