# How to use it?
# docker-compose --env-file .env.local  up 

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/memorush
  memorush-spring:
    build:
      context: ./memorush-spring
      dockerfile: ./docker/production/Dockerfile
    environment:
      PROFILE_ACTIVE: ${PROFILE_ACTIVE:-h2}
      ADMIN_NAME: ${ADMIN_NAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
      POSTGRES_URL: jdbc:postgresql://memorush-db:5432/postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ALLOWED_ORIGINS_ARRAY: ${ALLOWED_ORIGINS_ARRAY:-http://localhost:3000}
      POSTGRES_DDL_AUTO: ${POSTGRES_DDL_AUTO:-update}
    depends_on:
      - memorush-db
      - memorush-pgadmin
    networks:
      - memorush

  memorush-react:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        # Change me!
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:8080}
    networks:
     - memorush

  memorush-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - memorush-db:/data/postgres
    networks:
      - memorush
    restart: unless-stopped

  memorush-pgadmin:
    container_name: memorush-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - memorush-pgadmin:/var/lib/pgadmin
    depends_on:
      - memorush-db
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - memorush
    restart: unless-stopped

networks:
  memorush:
    driver: bridge

volumes:
  memorush-db:
  memorush-pgadmin: